source 'https://rubygems.org'

gem 'rails', '5.0'
gem 'puma', '~> 3.0'
gem 'pg', '~> 0.18.4'
gem 'rack-cors', '~> 0.4.0'
gem 'octokit'
gem 'virtus'
gem 'jwt', '~> 1.5.4'
gem 'newrelic_rpm', '~> 3.17.1'


group :development, :test do
  gem 'pry-rails'
  gem 'pry-stack_explorer'
  gem 'pry-byebug'
end

group :development do
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
